# Site settings
title: All About Junjie
description: All (or most) about Junjie, a software Engineer.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Junjie Zhang
user_description: Engineer & Masterâ€™s degrees specialized in autonomous systems. Hands-on experience in leading Chinese tech companies, focusing on autonomous driving algorithms, deep learning and software development. Passionate about AI, intelligent systems and software engineering, with strong adaptability, self-motivation, and constant drive to learn and contribute in fast-evolving environments.
user_title: Software Developer
email: iya.zhangjj@gmail.com
# twitter_username: lorem_ipsum
github_username:  Junjie-Iya
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
